table _FOCUS_VIEW_
	lineageTag: 14a4a088-a6a4-4ba4-9763-923446a51687

	column _ship_id
		dataType: int64
		formatString: 0
		lineageTag: 17229720-c74c-483a-950b-0098c0c71314
		summarizeBy: sum
		sourceColumn: _ship_id

		annotation SummarizationSetBy = Automatic

	column _iss_dom
		dataType: string
		lineageTag: cd522bec-5464-436a-9f01-31f44e3b75e8
		summarizeBy: none
		sourceColumn: _iss_dom

		annotation SummarizationSetBy = Automatic

	column _fo_id_coms
		dataType: string
		lineageTag: 4dfa0752-0316-4403-9d02-7d66c728ec91
		summarizeBy: none
		sourceColumn: _fo_id_coms

		annotation SummarizationSetBy = Automatic

	column _fo_no
		dataType: string
		lineageTag: cf7dbfd7-6b41-40fa-b2f7-dbafad33bc0f
		summarizeBy: none
		sourceColumn: _fo_no

		annotation SummarizationSetBy = Automatic

	column _fo_comments
		dataType: string
		lineageTag: 971180f1-726d-47f0-a3f5-7d6025bccad9
		summarizeBy: none
		sourceColumn: _fo_comments

		annotation SummarizationSetBy = Automatic

	column _creation_date
		dataType: dateTime
		formatString: yyyy-mmm-dd
		lineageTag: e9d2ac46-28c5-44d2-8872-85b84194a37d
		summarizeBy: none
		sourceColumn: _creation_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column _origin
		dataType: string
		lineageTag: 9323f157-f6a3-4031-9b53-838f755e0535
		summarizeBy: none
		sourceColumn: _origin

		annotation SummarizationSetBy = Automatic

	column _destination
		dataType: string
		lineageTag: 643481c2-f030-49c6-9abe-ead4ccd8cd17
		summarizeBy: none
		sourceColumn: _destination

		annotation SummarizationSetBy = Automatic

	column _crm_client
		dataType: string
		lineageTag: 631b9649-9dbc-4000-85ec-b7840e26ceb5
		summarizeBy: none
		sourceColumn: _crm_client

		annotation SummarizationSetBy = Automatic

	column _crm_client_branch
		dataType: string
		lineageTag: 8a5d6032-243f-4cf9-95a4-297bd20a64a5
		summarizeBy: none
		sourceColumn: _crm_client_branch

		annotation SummarizationSetBy = Automatic

	column _lob
		dataType: string
		lineageTag: c52ea39c-cc00-4541-9bf6-849878c731be
		summarizeBy: none
		sourceColumn: _lob

		annotation SummarizationSetBy = Automatic

	column _departure_date
		dataType: dateTime
		formatString: yyyy-mmm-dd
		lineageTag: 165226b3-a413-4447-817e-dcaa3e117807
		summarizeBy: none
		sourceColumn: _departure_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column _eta
		dataType: dateTime
		formatString: yyyy-mmm-dd
		lineageTag: 03cf7bd2-ce93-4c67-a492-ed48ee51c353
		summarizeBy: none
		sourceColumn: _eta

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isCustom":true}

	column _eta_wakeo
		dataType: dateTime
		formatString: yyyy-mmm-dd
		lineageTag: 89273ffa-febc-45e4-85e3-f0bccf470802
		summarizeBy: none
		sourceColumn: _eta_wakeo

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _etd
		dataType: dateTime
		formatString: yyyy-mmm-dd
		lineageTag: ea57e1a1-5f6a-4295-a52f-8683b6bd1aa5
		summarizeBy: none
		sourceColumn: _etd

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _etd_wakeo
		dataType: dateTime
		formatString: yyyy-mmm-dd
		lineageTag: 506f02df-4a9d-4d3e-ba89-8be3965f4889
		summarizeBy: none
		sourceColumn: _etd_wakeo

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _arrival_date
		dataType: dateTime
		formatString: yyyy-mmm-dd
		lineageTag: 8e646972-e84c-48af-b518-81aecaf9ebb0
		summarizeBy: none
		sourceColumn: _arrival_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _delivery_date
		dataType: dateTime
		formatString: yyyy-mmm-dd
		lineageTag: 3a934b8f-e107-41e6-a964-fdb59cda7248
		summarizeBy: none
		sourceColumn: _delivery_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _pickup_date
		dataType: dateTime
		formatString: yyyy-mmm-dd
		lineageTag: 90daf44d-4330-46dc-b058-aea491acb65e
		summarizeBy: none
		sourceColumn: _pickup_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _do_date
		dataType: dateTime
		formatString: yyyy-mmm-dd
		lineageTag: 431a8b42-c5b5-4e55-bbb5-ba7be01b7081
		summarizeBy: none
		sourceColumn: _do_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _do_exp_date
		dataType: dateTime
		formatString: yyyy-mmm-dd
		lineageTag: ead6bb5a-490a-4d1b-878f-34a29348cf31
		summarizeBy: none
		sourceColumn: _do_exp_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _ptd
		dataType: dateTime
		formatString: yyyy-mmm-dd
		lineageTag: fdfb67ec-1d1f-400a-8ba6-854997044e29
		summarizeBy: none
		sourceColumn: _ptd

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _ptd_source
		dataType: string
		lineageTag: aefee7d8-26bc-4e79-9455-a3f68cf80272
		summarizeBy: none
		sourceColumn: _ptd_source

		annotation SummarizationSetBy = Automatic

	column _pta
		dataType: dateTime
		formatString: yyyy-mmm-dd
		lineageTag: 52e59683-14e0-46a9-97d9-c715a813b8c7
		summarizeBy: none
		sourceColumn: _pta

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _pta_source
		dataType: string
		lineageTag: e208f97a-9baa-4571-b4df-a66e21e3d49c
		summarizeBy: none
		sourceColumn: _pta_source

		annotation SummarizationSetBy = Automatic

	column _crd_actual
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6aedbe34-b994-43e2-baf3-14d710e35657
		summarizeBy: none
		sourceColumn: _crd_actual

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _crd_estimated
		dataType: dateTime
		formatString: Long Date
		lineageTag: b57eb73d-769b-4bf2-974a-b751b01cb360
		summarizeBy: none
		sourceColumn: _crd_estimated

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column _branch_bu
		dataType: string
		lineageTag: 89620e0f-8786-4f4a-9ac6-3edee28219dd
		summarizeBy: none
		sourceColumn: _branch_bu

		annotation SummarizationSetBy = Automatic

	column _supplier
		dataType: string
		lineageTag: 054ed771-e700-4b09-a0dd-de3a422b671f
		summarizeBy: none
		sourceColumn: _supplier

		annotation SummarizationSetBy = Automatic

	column _master_line
		dataType: string
		lineageTag: a383fe58-bd00-4fb0-8434-f0e22338b07c
		summarizeBy: none
		sourceColumn: _master_line

		annotation SummarizationSetBy = Automatic

	column _item_desc
		dataType: string
		lineageTag: fdd9e207-6705-4d26-b5b2-dcb2f6b75454
		summarizeBy: none
		sourceColumn: _item_desc

		annotation SummarizationSetBy = Automatic

	column _transport_mode
		dataType: string
		lineageTag: edb808d7-fa76-4871-966c-62193976883a
		summarizeBy: none
		sourceColumn: _transport_mode

		annotation SummarizationSetBy = Automatic

	column _direction
		dataType: string
		lineageTag: ea984258-e5ed-4901-854e-f740f7de498d
		summarizeBy: none
		sourceColumn: _direction

		annotation SummarizationSetBy = Automatic

	column _routed_by
		dataType: string
		lineageTag: c23d1cc5-0757-4f4c-b789-f0d19dc7dc40
		summarizeBy: none
		sourceColumn: _routed_by

		annotation SummarizationSetBy = Automatic

	column _incoterms
		dataType: string
		lineageTag: cdf807bd-8c65-47a7-94d5-81763d1fb92b
		summarizeBy: none
		sourceColumn: _incoterms

		annotation SummarizationSetBy = Automatic

	column _shipment_serial_no
		dataType: string
		lineageTag: 29ff8694-716e-4564-93f8-7ca1fd6f0031
		summarizeBy: none
		sourceColumn: _shipment_serial_no

		annotation SummarizationSetBy = Automatic

	column _master_no
		dataType: string
		lineageTag: 3bc1ca35-ddfe-4060-b982-4265219d331d
		summarizeBy: none
		sourceColumn: _master_no

		annotation SummarizationSetBy = Automatic

	column _house_no
		dataType: string
		lineageTag: f14d02ba-bf84-4246-81a4-536129462612
		summarizeBy: none
		sourceColumn: _house_no

		annotation SummarizationSetBy = Automatic

	column _carrier
		dataType: string
		lineageTag: a6d25257-d49b-4664-93e7-7e136864e6a0
		summarizeBy: none
		sourceColumn: _carrier

		annotation SummarizationSetBy = Automatic

	column _commodity
		dataType: string
		lineageTag: ee66d89d-df6e-414a-9b47-c5eb271f17d9
		summarizeBy: none
		sourceColumn: _commodity

		annotation SummarizationSetBy = Automatic

	column _origin_region
		dataType: string
		lineageTag: 6ecd2a84-2a03-4505-aab4-8e73beb43fbc
		summarizeBy: none
		sourceColumn: _origin_region

		annotation SummarizationSetBy = Automatic

	column _origin_country_name
		dataType: string
		lineageTag: 56a6c84d-002f-40c8-86d8-655e34512528
		summarizeBy: none
		sourceColumn: _origin_country_name

		annotation SummarizationSetBy = Automatic

	column _origin_country_code
		dataType: string
		lineageTag: 5f704692-68dc-4e84-80fa-f1be816733f1
		summarizeBy: none
		sourceColumn: _origin_country_code

		annotation SummarizationSetBy = Automatic

	column _origin_port_code
		dataType: string
		lineageTag: 13798075-07c8-478c-a1a1-607b577e7fff
		summarizeBy: none
		sourceColumn: _origin_port_code

		annotation SummarizationSetBy = Automatic

	column _destination_region
		dataType: string
		lineageTag: 98eb1df2-5b26-4a57-b960-0cedb719d694
		summarizeBy: none
		sourceColumn: _destination_region

		annotation SummarizationSetBy = Automatic

	column _destination_country_name
		dataType: string
		lineageTag: 65de25b4-7faa-4f6e-8974-d7adbe7ab012
		summarizeBy: none
		sourceColumn: _destination_country_name

		annotation SummarizationSetBy = Automatic

	column _destination_country_code
		dataType: string
		lineageTag: 9692b3fb-5e9d-420c-a764-93d6db69996e
		summarizeBy: none
		sourceColumn: _destination_country_code

		annotation SummarizationSetBy = Automatic

	column _destination_port_code
		dataType: string
		lineageTag: 49fb3b9e-f263-478f-8fe9-965ae0f0a31c
		summarizeBy: none
		sourceColumn: _destination_port_code

		annotation SummarizationSetBy = Automatic

	column _container_ids
		dataType: string
		lineageTag: ebde12ea-0be9-4c03-a27b-c051012cd573
		summarizeBy: none
		sourceColumn: _container_ids

		annotation SummarizationSetBy = Automatic

	column _container_type
		dataType: string
		lineageTag: ad2fe153-6cd6-410f-8e79-cc7a86c5cc92
		summarizeBy: none
		sourceColumn: _container_type

		annotation SummarizationSetBy = Automatic

	column _20_ft
		dataType: int64
		formatString: 0
		lineageTag: c33524b9-3a49-4604-a364-57b9ac020ae3
		summarizeBy: sum
		sourceColumn: _20_ft

		annotation SummarizationSetBy = Automatic

	column _40_ft
		dataType: int64
		formatString: 0
		lineageTag: f0c4bc2e-dea1-4f0f-89a3-d6056e7e0189
		summarizeBy: sum
		sourceColumn: _40_ft

		annotation SummarizationSetBy = Automatic

	column _total_count
		dataType: int64
		formatString: 0
		lineageTag: 8447f971-306a-473d-beda-781a8013939f
		summarizeBy: sum
		sourceColumn: _total_count

		annotation SummarizationSetBy = Automatic

	column _teu
		dataType: double
		lineageTag: 669abf8d-b615-4b5a-9369-a708303f6d71
		summarizeBy: sum
		sourceColumn: _teu

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _cargo_ho
		dataType: string
		lineageTag: 29fdd761-3ee7-4163-b8a3-8d4f4943be42
		summarizeBy: none
		sourceColumn: _cargo_ho

		annotation SummarizationSetBy = Automatic

	column _status
		dataType: string
		lineageTag: 29cf04a6-f954-40e9-9ca2-ef04cd54a678
		summarizeBy: none
		sourceColumn: _status

		annotation SummarizationSetBy = Automatic

	column _delivery_location
		dataType: string
		lineageTag: 7d6056d5-0e36-4195-83a5-72d89fa9be39
		summarizeBy: none
		sourceColumn: _delivery_location

		annotation SummarizationSetBy = Automatic

	column _po_outer_qnty
		dataType: string
		lineageTag: 0fe67cbc-ec07-4dfe-9611-7d35075ded11
		summarizeBy: none
		sourceColumn: _po_outer_qnty

		annotation SummarizationSetBy = Automatic

	column _po_inner_qnty
		dataType: string
		lineageTag: 2bef5806-6ab2-4950-bdae-2de2039f8d87
		summarizeBy: none
		sourceColumn: _po_inner_qnty

		annotation SummarizationSetBy = Automatic

	column _outer_qnty_shipped
		dataType: string
		lineageTag: 5a92609e-7fb5-4452-b422-fb518cddfb90
		summarizeBy: none
		sourceColumn: _outer_qnty_shipped

		annotation SummarizationSetBy = Automatic

	column _inner_qnty_shipped
		dataType: string
		lineageTag: 4d8a4e08-0fb1-4c4f-a13b-acc60ce661bc
		summarizeBy: none
		sourceColumn: _inner_qnty_shipped

		annotation SummarizationSetBy = Automatic

	column _cbm
		dataType: double
		lineageTag: 5da0c0b8-4b5c-42f4-bb00-4a8bf824a19d
		summarizeBy: sum
		sourceColumn: _cbm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _gross_weight
		dataType: double
		lineageTag: 0707f62a-7bc9-4020-bcac-082d2a396e64
		summarizeBy: sum
		sourceColumn: _gross_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _charge_weight
		dataType: double
		lineageTag: 52006b80-26a2-4481-b508-3d1ffacd1b16
		summarizeBy: sum
		sourceColumn: _charge_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _packages
		dataType: double
		lineageTag: e5e43317-4a60-48fd-a522-bd002f59b3fd
		summarizeBy: sum
		sourceColumn: _packages

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _package_type
		dataType: string
		lineageTag: 84496b11-f515-47d7-a2ef-c113041cd955
		summarizeBy: none
		sourceColumn: _package_type

		annotation SummarizationSetBy = Automatic

	column _customs_declared_currency
		dataType: string
		lineageTag: 063d6dac-17cf-4ce7-80aa-c6515df37a72
		summarizeBy: none
		sourceColumn: _customs_declared_currency

		annotation SummarizationSetBy = Automatic

	column _customs_invoice_aed
		dataType: double
		lineageTag: 967e02ab-725e-42c1-bb69-427fee663892
		summarizeBy: sum
		sourceColumn: _customs_invoice_aed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column _remarks
		dataType: string
		lineageTag: a687ba87-affd-4ce2-ae96-ace1fdd2fd60
		summarizeBy: none
		sourceColumn: _remarks

		annotation SummarizationSetBy = Automatic

	column _debit_note
		dataType: string
		lineageTag: 9bb394b7-0f37-4f0d-9f96-e5140a097aa9
		summarizeBy: none
		sourceColumn: _debit_note

		annotation SummarizationSetBy = Automatic

	column _ontime_order_placement_perf
		dataType: string
		lineageTag: b2a32160-5b74-47ab-91a8-d359a37e854d
		summarizeBy: none
		sourceColumn: _ontime_order_placement_perf

		annotation SummarizationSetBy = Automatic

	column _supplier_committed_prod_rdy_perf
		dataType: string
		lineageTag: 79e8e6bb-1c0a-43e7-b74d-1f4d06b8b105
		summarizeBy: none
		sourceColumn: _supplier_committed_prod_rdy_perf

		annotation SummarizationSetBy = Automatic

	column _iss_cont_booking_perf
		dataType: string
		lineageTag: ccad9ae3-c097-49bd-bbef-ff85f2dad7d0
		summarizeBy: none
		sourceColumn: _iss_cont_booking_perf

		annotation SummarizationSetBy = Automatic

	column _iss_transit_lead_time_perf
		dataType: string
		lineageTag: 80c6f2d0-3f74-4683-9386-bd83e805fb93
		summarizeBy: none
		sourceColumn: _iss_transit_lead_time_perf

		annotation SummarizationSetBy = Automatic

	column _iss_custom_clear_perf
		dataType: string
		lineageTag: 5d2444d7-a0b7-4685-b1fe-776139ff4908
		summarizeBy: none
		sourceColumn: _iss_custom_clear_perf

		annotation SummarizationSetBy = Automatic

	column _e2e_total_lead_time_perf
		dataType: string
		lineageTag: 7963af4f-5434-4067-934d-a1f9fcc3d96e
		summarizeBy: none
		sourceColumn: _e2e_total_lead_time_perf

		annotation SummarizationSetBy = Automatic

	column _days_total_comm_perf
		dataType: string
		lineageTag: 4db45914-dc86-418b-978c-422ff214f06c
		summarizeBy: none
		sourceColumn: _days_total_comm_perf

		annotation SummarizationSetBy = Automatic

	column _actual_lead
		dataType: string
		lineageTag: 1cc6d3da-42e8-4f7e-97ce-17ab2a3e8e41
		summarizeBy: none
		sourceColumn: _actual_lead

		annotation SummarizationSetBy = Automatic

	column _health_check
		dataType: string
		lineageTag: 887971e7-4ba9-4b6a-a538-947f6d812f51
		summarizeBy: none
		sourceColumn: _health_check

		annotation SummarizationSetBy = Automatic

	column _reason_code
		dataType: string
		lineageTag: 4f19819b-d413-462f-91cd-57acfef66864
		summarizeBy: none
		sourceColumn: _reason_code

		annotation SummarizationSetBy = Automatic

	column _days_order_placement_lt
		dataType: string
		lineageTag: e496ed12-f9a5-40c0-944d-235469587286
		summarizeBy: none
		sourceColumn: _days_order_placement_lt

		annotation SummarizationSetBy = Automatic

	column _days_supplier_production_lt
		dataType: string
		lineageTag: 5db4d430-9d2d-4ee7-8b51-187050e7617c
		summarizeBy: none
		sourceColumn: _days_supplier_production_lt

		annotation SummarizationSetBy = Automatic

	column _days_custom_clearance_lt
		dataType: string
		lineageTag: 886037d1-2485-412f-9326-70a766785289
		summarizeBy: none
		sourceColumn: _days_custom_clearance_lt

		annotation SummarizationSetBy = Automatic

	column _days_iss_cont_booking_lt
		dataType: string
		lineageTag: 0e22e99d-1291-453f-8bbc-377df7f493d9
		summarizeBy: none
		sourceColumn: _days_iss_cont_booking_lt

		annotation SummarizationSetBy = Automatic

	column _days_transit_lt
		dataType: string
		lineageTag: 2baca59a-d756-4be0-b3b1-5afcb150fa66
		summarizeBy: none
		sourceColumn: _days_transit_lt

		annotation SummarizationSetBy = Automatic

	column _e2e_total_lt
		dataType: string
		lineageTag: fe0925a3-4626-4e08-a694-2b80896ef7ac
		summarizeBy: none
		sourceColumn: _e2e_total_lt

		annotation SummarizationSetBy = Automatic

	column _p2p_value_usd
		dataType: string
		lineageTag: b53834a7-d83d-4b37-9e25-8289dbb54d69
		summarizeBy: none
		sourceColumn: _p2p_value_usd

		annotation SummarizationSetBy = Automatic

	column _spo_number
		dataType: string
		lineageTag: 0d53c1ef-e873-4758-86eb-27c06a6aa00e
		summarizeBy: none
		sourceColumn: _spo_number

		annotation SummarizationSetBy = Automatic

	column _po_status
		dataType: string
		lineageTag: 7263bcc9-f780-45f4-a7aa-d045706beb78
		summarizeBy: none
		sourceColumn: _po_status

		annotation SummarizationSetBy = Automatic

	column _dep_discrepancy_days
		dataType: string
		lineageTag: 9b5d0c87-d714-4099-a49b-ae47f8c833c1
		summarizeBy: none
		sourceColumn: _dep_discrepancy_days

		annotation SummarizationSetBy = Automatic

	column _arr_discrepancy_days
		dataType: string
		lineageTag: 545436dd-8eaf-4202-9a60-522019ec152a
		summarizeBy: none
		sourceColumn: _arr_discrepancy_days

		annotation SummarizationSetBy = Automatic

	column _rdd_eta
		dataType: string
		lineageTag: ad0b87cd-0880-403c-910e-9c380efe0bf0
		summarizeBy: none
		sourceColumn: _rdd_eta

		annotation SummarizationSetBy = Automatic

	column _nbd_2_crd
		dataType: string
		lineageTag: cd5dc792-d34f-426e-861d-1b0eb58ae96a
		summarizeBy: none
		sourceColumn: _nbd_2_crd

		annotation SummarizationSetBy = Automatic

	column _po_2_crd
		dataType: string
		lineageTag: dd06e9ca-c2b8-427b-8b0f-82bb20cd299e
		summarizeBy: none
		sourceColumn: _po_2_crd

		annotation SummarizationSetBy = Automatic

	column _crd_2_etd
		dataType: string
		lineageTag: f8458a2b-a12e-413c-9fcd-8c8d0737349e
		summarizeBy: none
		sourceColumn: _crd_2_etd

		annotation SummarizationSetBy = Automatic

	column _etd_2_eta
		dataType: string
		lineageTag: d5976e2f-9870-4710-abc3-ed2289b15261
		summarizeBy: none
		sourceColumn: _etd_2_eta

		annotation SummarizationSetBy = Automatic

	column _eta_2_del
		dataType: string
		lineageTag: eb220d96-9df4-44cd-b6d0-68dca4d949b2
		summarizeBy: none
		sourceColumn: _eta_2_del

		annotation SummarizationSetBy = Automatic

	column _nbd_2_eta
		dataType: string
		lineageTag: 739da22f-9fc7-42bd-8a2f-7eaffe73e167
		summarizeBy: none
		sourceColumn: _nbd_2_eta

		annotation SummarizationSetBy = Automatic

	column _nbd_2_del
		dataType: string
		lineageTag: 24a140bb-4ef2-46f6-8b99-8c562825b712
		summarizeBy: none
		sourceColumn: _nbd_2_del

		annotation SummarizationSetBy = Automatic

	column _avg_lt
		dataType: string
		lineageTag: 6c66ff59-99a4-43e4-bd35-f2234318417f
		summarizeBy: none
		sourceColumn: _avg_lt

		annotation SummarizationSetBy = Automatic

	column _line_id
		dataType: string
		lineageTag: b3c07d73-aead-4443-ad97-b288faace2e8
		summarizeBy: none
		sourceColumn: _line_id

		annotation SummarizationSetBy = Automatic

	partition _FOCUS_VIEW_ = m
		mode: import
		queryGroup: TABLES
		source = ```
				let
				    Source = PostgreSQL.Database("c-powerbicosmos.k4mjimliu3npzv.postgres.cosmos.azure.com", "powerbi", 
				    
				                            [Query = FOCUS_SQL_SOURCE[_code]{0}]),
				
				
				    #"Changed Type" = Table.TransformColumnTypes(Source,{
				                                                            {"_creation_date", type date}, {"_departure_date", type date}, {"_eta", type date}
				                                                            , {"_eta_wakeo", type date}, {"_etd", type date}, {"_etd_wakeo", type date}, {"_arrival_date", type date}
				                                                            , {"_delivery_date", type date}, {"_pickup_date", type date}, {"_do_date", type date}, {"_do_exp_date", type date}
				                                                            , {"_ptd", type date}, {"_pta", type date}, {"_crd_actual", type date}, {"_crd_estimated", type date}
				                                                        }),
				    
				    _filter_branch = Table.SelectRows(#"Changed Type", each [_crm_client_branch] = "EMIRATES AIRLINE - DEPARTMENT - INFLIGHT SERVICES"),
				
				    _filter_date = Table.SelectRows(_filter_branch, (x) => x[_creation_date] >= #date(2026,8,1) or x[_arrival_date] >= #date(2026,8,1))
				
				in
				    _filter_date
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

